# Generated by Django 4.2.25 on 2025-10-31 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=2040, unique=True)),
                ('verdict', models.CharField(choices=[('Malveillant', 'Malveillant'), ('Légitime', 'Legitime'), ('Suspect', 'Suspect'), ('Inconnu', 'Inconnu')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_analyse', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeBlanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=2040, unique=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='URLMalveillants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=2040, unique=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
